name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        env:
          BROKER_HOSTNAME: ${{ secrets.BROKER_HOSTNAME }}
          BROKER_PROTOCOL: ${{ secrets.BROKER_PROTOCOL  }}
          BROKER_USERNAME: ${{ secrets.BROKER_USERNAME  }}
          BROKER_PASSWORD: ${{ secrets.BROKER_PASSWORD  }}
          BROKER_PORT: ${{ secrets.BROKER_PORT  }}
        run: cat $HOME/secrets/my_secret.json
        run: yarn test --ci --maxWorkers=2

      - name: Build
        run: yarn build
